## Numpy Tutorial

- used for creating multidimensional  array

In [1]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)



In [5]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [11]:
# tells the column and rows
arr.shape


(5,)

In [22]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[9,8,7,6,5]

arr = np.array([list1,list2,list3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [15]:
arr.shape

(3, 5)

In [19]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 8],
       [7, 6, 5]])

### Indexing

In [20]:
arr = np.array([1,2,3,4,5])

In [21]:
arr[3]

np.int64(4)

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [24]:
arr[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [27]:
arr[1:,3:]

array([[5, 6],
       [6, 5]])

In [28]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [31]:
arr = np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [35]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Copy function and broadcasting

In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [42]:
arr[3:] = 100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [43]:
arr1 = arr

In [44]:
arr1[3:] = 500
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [45]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [49]:
arr1 = arr.copy()

In [51]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


### conditions for EDA

In [55]:
arr<2
arr[arr<300]


array([1, 2, 3])

In [57]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [65]:
np.random.rand(3,3)

array([[0.91080474, 0.54661205, 0.45561796],
       [0.00882273, 0.89753735, 0.19621533],
       [0.527115  , 0.18104206, 0.65619159]])